import Head from "next/head";
import { Inter } from "@next/font/google";
// import styles from "@/styles/Home.module.css";
import NavbarApp from "@/component/navbar";
import Row from "react-bootstrap/Row";
import Col from "react-bootstrap/Col";
import BgHeader from "../../assets/bg_header.jpg";
import Image from "next/image";
import { Button } from "react-bootstrap";
import IconHours from "../../assets/icon_hours.png";

import CardFeatures from "../component/cardFeatures";
import CardPrice from "@/component/cardPrice";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavbarApp />
      <br />
      <Row>
        <Col style={{ alignSelf: "center", textAlign: "center" }} sm={6}>
          <h1>Website Undangan Pernikahan</h1>
          <h3>
            Undang teman-teman terdekat anda untuk menghadiri pernikahan yang
            akan kalian laksanakan
          </h3>
          <br />
          <br />
          <Button variant="primary" style={{ fontSize: 26 }}>
            Buat Undangan Sekarang!
          </Button>
        </Col>
        <Col sm={6}>
          <Image
            src={BgHeader}
            style={{ width: "100%", height: 400 }}
            className="Background"
            alt="Background"
          />
        </Col>
      </Row>
      <br />
      <Row style={{ textAlign: "center" }}>
        <Col sm={6}>
          <h2>Undangan Digital No. 1 Indonesia</h2>
          <h4>
            Cara termudah dan tercepat untuk membuat undangan pernikahan anda
            dalam bentuk website yang menarik dan elegant
          </h4>
          <h3>Kami ada di : Facebook, Instagram dan Youtube</h3>
        </Col>
        <Col sm={3}>
          <Row>
            <h3>Undangan Aktif</h3>
          </Row>
          <Row>
            <h3>Jumlah Ucapan</h3>
          </Row>
        </Col>
        <Col sm={3}>
          <Row>
            <h3>Jumlah Pengguna</h3>
          </Row>
          <Row></Row>
        </Col>
      </Row>
      <br />
      <Row style={{ textAlign: "center" }}>
        <Col sm={6}>
          <h2>Cara Membuat Undangan</h2>
          <p>
            Hanya dalam hitungan menit undangan pernikahan kamu langsung jadi
          </p>
          <li>Registrasi terlebih dahulu</li>
          <li>Isi data diri</li>
          <li>Pilih template atau tema</li>
          <li>Aktifkan dan website undangan kamu siap digunakan</li>
        </Col>
        <Col sm={6}>
          <h2>Tutorial Video</h2>
        </Col>
      </Row>
      <br />
      <Row>
        <h2>Fitur yang tersedia di Jadi Pelaminan</h2>

        <Col sm={2} style={{ display: "flex", justifyContent: "center" }}>
          <CardFeatures
            title={"CountDown"}
            value={
              "Jalankan music sebagai background untuk memberi effect romansa saat melihat undangan anda"
            }
            image={IconHours}
          />
        </Col>
        <Col sm={2} style={{ display: "flex", justifyContent: "center" }}>
          <CardFeatures
            title={"CountDown"}
            value={
              "Jalankan music sebagai background untuk memberi effect romansa saat melihat undangan anda"
            }
            image={IconHours}
          />
        </Col>
        <Col sm={2} style={{ display: "flex", justifyContent: "center" }}>
          <CardFeatures
            title={"CountDown"}
            value={
              "Jalankan music sebagai background untuk memberi effect romansa saat melihat undangan anda"
            }
            image={IconHours}
          />
        </Col>
        <Col sm={2} style={{ display: "flex", justifyContent: "center" }}>
          <CardFeatures
            title={"CountDown"}
            value={
              "Jalankan music sebagai background untuk memberi effect romansa saat melihat undangan anda"
            }
            image={IconHours}
          />
        </Col>
        <Col sm={2} style={{ display: "flex", justifyContent: "center" }}>
          <CardFeatures
            title={"CountDown"}
            value={
              "Jalankan music sebagai background untuk memberi effect romansa saat melihat undangan anda"
            }
            image={IconHours}
          />
        </Col>
        <Col sm={2} style={{ display: "flex", justifyContent: "center" }}>
          <CardFeatures
            title={"CountDown"}
            value={
              "Jalankan music sebagai background untuk memberi effect romansa saat melihat undangan anda"
            }
            image={IconHours}
          />
        </Col>
      </Row>
      <br />
      <Row style={{ display: "flex", justifyContent: "center" }}>
        <h2>Tersedia 30 Desain terbaik untuk anda</h2>
        <Col sm={4} style={{ display: "flex", justifyContent: "center" }}>
          <Image src={BgHeader} style={{ width: "100%", height: 150 }} />
        </Col>
        <Col sm={4} style={{ display: "flex", justifyContent: "center" }}>
          <Image src={BgHeader} style={{ width: "100%", height: 150 }} />
        </Col>
        <Col sm={4} style={{ display: "flex", justifyContent: "center" }}>
          <Image src={BgHeader} style={{ width: "100%", height: 150 }} />
        </Col>
      </Row>
      <br />
      <Row style={{ display: "flex", justifyContent: "center" }}>
        <Col sm={4} style={{ display: "flex", justifyContent: "center" }}>
          <Image src={BgHeader} style={{ width: "100%", height: 150 }} />
        </Col>
        <Col sm={4} style={{ display: "flex", justifyContent: "center" }}>
          <Image src={BgHeader} style={{ width: "100%", height: 150 }} />
        </Col>
        <Col sm={4} style={{ display: "flex", justifyContent: "center" }}>
          <Image src={BgHeader} style={{ width: "100%", height: 150 }} />
        </Col>
      </Row>

      <br />
      <Row style={{ display: "flex", justifyContent: "center" }}>
        <Button
          variant="primary"
          style={{
            fontSize: 26,
            width: "70%",
          }}
        >
          Lihat lebih banyak desain!
        </Button>
      </Row>
      <br />
      <Row>
        <h2>Harga Terbaik dengan Kualitas Terbaik</h2>

        <Col sm={4} style={{ display: "flex", justifyContent: "center" }}>
          <CardPrice
            image={IconHours}
            title={"Fitur"}
            value={"Preset/ Desain Standar"}
            textButton={"BASIC"}
            colorButton={"blue"}
          />
        </Col>
        <Col sm={4} style={{ display: "flex", justifyContent: "center" }}>
          <CardPrice
            image={IconHours}
            title={"Fitur"}
            value={"Preset/ Desain Standar"}
            textButton={"PREMIUM"}
            colorButton={"red"}
          />
        </Col>
        <Col sm={4} style={{ display: "flex", justifyContent: "center" }}>
          <CardPrice
            image={IconHours}
            title={"Fitur"}
            value={"Preset/ Desain Standar"}
            textButton={"EKSKLUSIF"}
            colorButton={"orange"}
          />
        </Col>
      </Row>
      <br />
    </div>
  );
}
